name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    build-lint-format:
        runs-on: ubuntu-latest

        steps:
            - name: Récupération du code source
              uses: actions/checkout@v4

            - name: Cloner logic-qcm-plus
              run: git clone https://github.com/MarysaR/logic-qcm-plus.git ../logic-qcm-plus

            - name: Préparer vendor logic-qcm-plus
              run: |
                  mkdir -p vendor
                  cp -R ../logic-qcm-plus vendor/logic-qcm-plus

            - name: Préparer package CI
              run: cp package.ci.json package.json

            - name: Configuration Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Installation des dépendances
              run: npm ci

            - name: Compilation TypeScript
              run: npm run build

            - name: Lint avec ESLint
              run: npm run lint

            - name: Vérification Prettier
              run: npm run format -- --check
